jobs:
  integration-test-qa:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/qa2'
    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1
      - uses: actions/checkout@v4
      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Start service
        run: ENV=qa npm start &
      - name: Run tests
        run: node test/integration/delivery-locations-by-barcode.test.js